services:
  - type: web
    name: jewelry-management-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: jewelry-mgmt-db
          property: connectionString 